spring.application.name=BankManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/Bank
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp